meixi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mx/',include('mx.urls',namespace='mx'))
]

mx/urls.py
from django.conf.urls import url

from mx import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^pluscart/$', views.pluscart, name='pluscart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^removegood/$', views.removegood, name='removegood'),
    url(r'^goods/(\d+)/$', views.goods, name='goods'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^checkphone/$', views.checkphone, name='checkphone'),
    url(r'^checkself/$', views.checkself, name='checkself'),
    url(r'^checkall/$', views.checkall, name='checkall'),
    url(r'^makeorder/$', views.makeorder, name='makeorder'),  # 下单
    url(r'^orderlist/(\d+)/$', views.orderlist, name='orderlist'),
    url(r'^orderdetail/(.+)/$', views.orderdetail, name='orderdetail'),  # 订单详情
    url(r'^mine/$', views.mine, name='mine'),  # 订单详情
    url(r'^pay/$', views.pay, name='pay'),  # 支付
    url(r'^appnotify/$', views.appnotify, name='appnotify'),  # 支付完成后(服务器)
    url(r'^returnview/$', views.returnview, name='returnview'),  # 买家支付完成后回到AXF哪个页面(客户端)
]

mx/models.py
from django.db import models


# Create your models here.
class Slide(models.Model):
    img = models.CharField(max_length=256)


class User(models.Model):
    phone = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=256)
    token = models.CharField(max_length=256)


class Good(models.Model):
    img = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    des = models.CharField(max_length=256)
    gray = models.FloatField(default=1.0)
    price = models.FloatField()


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Good)
    num = models.IntegerField(default=1)
    isselect = models.BooleanField(default=True)

class Order(models.Model):
    user = models.ForeignKey(User)
    # 状态  -2退款 -1过期 0未付款 1已付款 2已发货 3未评价 4已评价
    status = models.IntegerField(default=0)
    # 创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    # 订单号
    identifier = models.CharField(max_length=256)
class Ordergoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(Good)
    # 商品规格
    num = models.IntegerField()

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title class="star"></title>
    <link rel="stylesheet" href="{% static 'css/shouwei.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}" type="text/css">
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/headerbar.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>

</head>
<body>

<div class="header">
    <div class="headerbar">
        <div class="hb_content">
            <div class="hb_con_left">
                {% if users %}
                    <a href="{% url 'mx:mine' %}" class="register">{{ users.phone }}</a>
                    <a href="{% url 'mx:logout' %}" class="login">退出</a>
                    <a href="{% url 'mx:mine' %}">订单查询</a>
                {% else %}
                    <a href="{% url 'mx:register' %}" class="register">注册</a>
                    <a href="{% url 'mx:login' %}" class="login">登录</a>
                {% endif %}
            </div>
            <div class="hb_con_right">
                <p>客服热线：4000-250-630</p>
                <div class="follow">
                    <img src="{% static 'img/star.png' %}">
                    <span>关注我们</span>
                    <div class="share">
                        <a href="" class="sina">
                            <img src="{% static 'img/fou_sina.gif' %}">
                            <span>新浪微博</span>
                        </a>
                        <a href="" class="weixin">
                            <img src="{% static 'img/fou_wechat.gif' %}">
                            <span>美西微信</span>
                        </a>
                    </div>
                </div>
                <div class="bag">
                    <a href="{% url 'mx:cart' %}">
                        <div class="bag_n">
                            <img src="{% static 'img/shopping.png' %}" class="bag_icon">
                            <span>购物袋（<t style="color: #8E0C3A;">{{ csn }}</t>）</span>
                            <img class="arrow" src="{% static 'img/xiabiao.png' %}">
                        </div>
                    </a>


                   {% if users %}
                        <div class="cart">
                            {% if csn %}
                                <p class="new_cart">有新的商品加入 快去购物袋查看吧</p>
                            {% else %}
                                <div class="cart_n">
                                    您的购物袋是空的
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="header_top">
    <div class="meiciapp">
        <a href=""><img src="{% static 'img/ewm_indexTop.png' %}"></a>
        <span><img src="{% static 'img/ewm_txt.png' %}"></span>
    </div>
    <div class="logo">
        <img src="{% static 'img/logo_new.png' %}">
    </div>
</div>
</div>

<div class="content">
    <div class="cart_img">
        <img src="{% static 'img/cart_sub.gif' %}">
    </div>
    {% if carts %}
        <div class="cart_ok">
            <div class="orderTips">
                <div class="orderTips_m">
                    <span class="goods_success"></span>
                </div>
            </div>
            <div class="cart_pro">
                <table width="100%">
                    <tbody>
                    <tr>
                        <th width="60px">
                            <div class="checkall" isall="true">
                                <img class="selfok" src="{% static 'img/ok.png' %}" alt="">
                            </div>
                        </th>
                        <th width="200px">商品图片</th>
                        <th width="100px">商品名称</th>
                        <th width="260px">数量</th>
                        <th width="60px">单价</th>
                        <th width="175px">总价</th>
                        <th>操作</th>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="cart_list">
                {% for cart in carts %}
                    <table width="100%" class="carttab">
                        <tbody>
                        <tr class="cartneir">
                            <th width="60px">
                                <div class="checkself" isselect="{{ cart.isselect }}" cartid="{{ cart.id }}">
                                    {% if cart.isselect %}
                                        <img class="isok" src="{% static 'img/ok.png' %}" alt="">
                                    {% else %}
                                        <img src="{% static 'img/no.png' %}" alt="">
                                    {% endif %}
                                </div>
                            </th>
                            <th width="200px"><img width="48px" src="{% static cart.goods.img %}" alt=""></th>
                            <th width="100px">{{ cart.goods.name }}</th>
                            <th width="260px">
                                <div class="g_r_num">
                                    <div class="g_r_num_d1">
                                        <span class="g_r_num_d1_l" goodid="{{ cart.goods.id }}">-</span>
                                        <input type="text" class="g_r_num_d1_c" disabled="readonly"
                                               value="{{ cart.num }}">
                                        <span class="g_r_num_d1_r" goodid="{{ cart.goods.id }}">+</span>

                                    </div>
                                </div>
                            </th>
                            <th width="60px" class="price">{{ cart.goods.price }}</th>
                            <th width="175px"><span class="prices"></span></th>
                            <th class="removegood" goodid="{{ cart.goods.id }}">删除</th>
                        </tr>
                        </tbody>
                    </table>
                {% endfor %}
            </div>

            <div class="cart_price">
                <p>总计：</p><span id="ssmp"></span>
                <span class="pay_goods"></span>
            </div>
            <div class="pay">
                <button class="jiesuan"></button>
            </div>

        </div>
    {% else %}
        <a href="{% url 'mx:goods' 1 %}">        <div class="cart_none">
            <div class="cart_none_user">
                <h3>购物袋内暂时没有商品,点击查看最新单品</h3>
            </div>
        </div></a>
    {% endif %}

</div>


<div class="all"></div>
<div class="success">
    支付成功!
    <p class="back">返回购物袋&lt;&lt; </p>
</div>
<div class="pay_success">
    <div class="pay_true">
        <p>您要结算吗?</p>
    </div>
    <button class="true">确定</button>
    <button class="false">取消</button>
</div>
<div class="footer">
    <div class="help">
        <ul>
            <li class="help_title">购物指南</li>
            <li><a href="">购物流程</a></li>
            <li><a href="">配送方式</a></li>
        </ul>
        <ul>
            <li class="help_title">支付方式</li>
            <li><a href="">如何付款</a></li>
            <li><a href="">发票制度</a></li>
        </ul>
        <ul>
            <li class="help_title">商品说明</li>
            <li><a href="">商品尺码</a></li>
            <li><a href="">商品包装</a></li>
        </ul>
        <ul>
            <li class="help_title">客服中心</li>
            <li><a href="">七天退还</a></li>
            <li><a href="">常见问题</a></li>
        </ul>
        <ul class="help_mid">
            <li style="padding-top: 13px;line-height: 26px;">
                <h5>订购热线</h5>
                <br>
                <h4>4000-250-630</h4>
            </li>
        </ul>
        <ul class="help_mid" style="width: 145px;">
            <li style="padding-top: 13px;">
                <span>在线客服</span>
                <div class="tel">
                    <a href=""><img src="{% static 'img/tencent.png' %}"></a>
                    <a href=""><img src="{% static 'img/erji.png' %}"></a>
                </div>
            </li>
        </ul>
        <ul class="help_mid" style="width: 190px;">
            <li class="scan">
                <p>美西时尚APP</p>
                <img src="{% static 'img/ewm_indexTop.png' %}">
            </li>
            <li class="scan" style="width: 72px;">
                <p>关注我们</p>
                <img src="{% static 'img/ewm_wx.png' %}" style="margin: 0;">
            </li>
        </ul>
    </div>
    <div class="sub_nav">
        <ul class="clearfix">
            <li><a href="{% url 'mx:index' %}" class="clearfix_a">首页</a></li>
            <li><a href="" class="clearfix_a">关于美西</a></li>
            <li><a href="" class="clearfix_a">媒体报道</a></li>
            <li><a href="" class="clearfix_a">正品保障</a></li>
            <li><a href="" class="clearfix_a">业务合作</a></li>
            <li><a href="" class="clearfix_a">隐私声明</a></li>
            <li><a href="" class="clearfix_a">加入美西</a></li>
            <li><a href="" class="clearfix_a">网站地图</a></li>
            <li><a href="" class="clearfix_a">联系我们</a></li>
        </ul>
    </div>
    <div class="copyright">
        <p>
            Copyright © 2008-2016 美西时尚-
            <a href="">高端时尚生活电商</a>
        </p>
        <p>
            <a href="">
                沪ICP备09001221号
            </a>
        </p>
    </div>
    <div class="safe">
        <a href=""><img src="{% static 'img/hy_83x30.png' %}"></a>
        <a href=""><img src="{% static 'img/ssgs.gif' %}"></a>
    </div>
</div>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/shouwei.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/headerbar.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
</head>
<body>

<div class="header">
    <div class="headerbar">
        <div class="hb_content">
            <div class="hb_con_left">
                {% if phone %}
                    <a href="#" class="register">{{ phone }}</a>
                    <a href="{% url 'mx:logout' %}" class="login">退出</a>
                    <a href="">订单查询</a>
                {% else %}
                    <a href="{% url 'mx:register' %}" class="register">注册</a>
                    <a href="{% url 'mx:login' %}" class="login">登录</a>
                {% endif %}
            </div>
            <div class="hb_con_right">
                <p>客服热线:4000-250-630</p>
                <div class="follow">
                    <img src="{% static 'img/star.png' %}">
                    <span>关注我们</span>
                    <div class="share">
                        <a href="" class="sina">
                            <img src="{% static 'img/fou_sina.gif' %}">
                            <span>新浪微博</span>
                        </a>
                        <a href="" class="weixin">
                            <img src="{% static 'img/fou_wechat.gif' %}">
                            <span>美西微信</span>
                        </a>
                    </div>
                </div>
                <div class="bag">
                    <a href="cart.html">
                        <div class="bag_n">
                            <img src="{% static 'img/shopping.png' %}" class="bag_icon">
                            <span>购物袋（<t style="color: #8E0C3A;">0</t>）</span>
                            <img class="arrow" src="{% static 'img/xiabiao.png' %}">
                        </div>
                    </a>


                    <div class="cart">
                        <div class="cart_n">
                            您的购物车是空的
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header_top">
        <div class="meiciapp">
            <a href=""><img src="{% static 'img/ewm_indexTop.png' %}"></a>
            <span><img src="{% static 'img/ewm_txt.png' %}"></span>
        </div>
        <div class="logo">
            <img src="{% static 'img/logo_new.png' %}">
        </div>
        <div class="search">
            <input type="text" placeholder="请输入您的关键词" maxlength="20">
            <img src="{% static 'img/search.png' %}">
        </div>
    </div>
</div>
<div class="content">
    <div class="content_box">
        <div class="absolute">
            <img src="{% static 'img/register_bg.png' %}">
        </div>
        <p class="voucher">手机验证完成即送<b>100</b>元代金券</p>
        <form class="registerform" action="{% url 'mx:login' %}" method="post" id="register-view">
            {% csrf_token %}
            <div class="register_box" id="register_box">
                <div class="input_zone">
                    <div class="input_l"><i>手&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机：</i></div>
                    <div class="input_r">
                        <input type="text" class="user_name" id="phone" name="phone" value=""
                               style="color: rgb(204, 204, 204);font-size: 12px;">
                    </div>
                </div>
                <div class="input_zone">
                    <div class="input_l"><i>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：</i></div>
                    <div class="input_r">
                        <input type="password" class="psw" name="password">
                    </div>
                </div>
                <div class="meici_tag">
                    <input class="input_login" type="checkbox" value="1">
                    <span style="color: #6C6C6C;display: inline-block;">下次自动登录</span>
                    <span class="float_r">忘记密码？</span>
                </div>
                <div class="meici_tag">
                    <button type="button" class="btn_register" id="subButton"> 登陆 </button>
                    <br>
                    <div style="margin-top: 5px;text-align: right;">

                        <a href="{% url 'mx:register' %}" style="color: #8E0C3A;">立即注册</a>
                    </div>
                    <p class="regInfo_msg"></p>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="footer">
    <div class="sub_nav">
        <ul class="clearfix">
            <li><a href="{% url 'mx:index' %}">首页</a></li>
            <li><a href="">关于美西</a></li>
            <li><a href="">媒体报道</a></li>
            <li><a href="">正品保障</a></li>
            <li><a href="">业务合作</a></li>
            <li><a href="">隐私声明</a></li>
            <li><a href="">加入美西</a></li>
            <li><a href="">网站地图</a></li>
            <li><a href="">联系我们</a></li>
        </ul>
    </div>
    <div class="copyright"></div>
    <div class="safe"></div>
</div>

</body>
</html>

templates/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'mx:orderlist' 0 %}">未付款[{{ waitpay }}]</a>
<a href="{% url 'mx:orderlist' 1 %}">已付款[{{ paydone }}]</a>
</body>
</html>

templates/orderdetail.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/orderdetail.js' %}"></script>
</head>
<body>
订单号：{{ order.identifier }}
<br>

{% for ordergoods in order.ordergoods_set.all %}
    <img src="{% static ordergoods.goods.img %}" alt="">
    {{ ordergoods.goods.name }}
    {{ ordergoods.goods.gray }}
    {{ ordergoods.goods.price }}
    {{ ordergoods.num }}
{% endfor %}
<br>
<p><a href="{% url 'mx:cart' %}">返回购物车</a></p>
{% if order.status == 0 %}
    <div id="pay" identifier="{{ order.identifier }}">
    付款
    <div/>
{% endif %}


</body>
</html>

templates/orderlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for order in orders %}
    <a href="{% url 'mx:orderdetail' order.identifier %}">{{ forloop.counter }}|{{ order.identifier }}</a>
    <span>
    {% if order.status == 0 %}
        未付款
    {% elif order.status == 1 %}
        已付款
    {% endif %}
    </span>
    <br>
{% endfor %}

</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/shouwei.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/register.css' %}" type="text/css">
    <script src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'js/headerbar.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
</head>
<body>

<div class="header">
    <div class="headerbar">
        <div class="hb_content">
            <div class="hb_con_left">
                {% if phone %}
                    <a href="#" class="register">{{ phone }}</a>
                    <a href="{% url 'mx:logout' %}" class="login">退出</a>
                    <a href="">订单查询</a>
                {% else %}
                    <a href="{% url 'mx:register' %}" class="register">注册</a>
                    <a href="{% url 'mx:login' %}" class="login">登录</a>
                {% endif %}
            </div>
            <div class="hb_con_right">
                <p>客服热线:4000-250-630</p>
                <div class="follow">
                    <img src="{% static 'img/star.png' %}">
                    <span>关注我们</span>
                    <div class="share">
                        <a href="" class="sina">
                            <img src="{% static 'img/fou_sina.gif' %}">
                            <span>新浪微博</span>
                        </a>
                        <a href="" class="weixin">
                            <img src="{% static 'img/fou_wechat.gif' %}">
                            <span>美西微信</span>
                        </a>
                    </div>
                </div>
                <div class="bag">
                    <a href="cart.html">
                        <div class="bag_n">
                            <img src="{% static 'img/shopping.png' %}" class="bag_icon">
                            <span>购物袋（<t style="color: #8E0C3A;">0</t>）</span>
                            <img class="arrow" src="{% static 'img/xiabiao.png' %}">
                        </div>
                    </a>


                    <div class="cart">
                        <div class="cart_n">
                            您的购物车是空的
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header_top">
        <div class="meiciapp">
            <a href=""><img src="{% static 'img/ewm_indexTop.png' %}"></a>
            <span><img src="{% static 'img/ewm_txt.png' %}"></span>
        </div>
        <div class="logo">
            <img src="{% static 'img/logo_new.png' %}">
        </div>
        <div class="search">
            <input type="text" placeholder="请输入您的关键词" maxlength="20">
            <img src="{% static 'img/search.png' %}">
        </div>
    </div>
</div>
<div class="content">
    <div class="content_box">
        <div class="absolute">
            <img src="{% static 'img/register_bg.png' %}">
        </div>
        <p class="voucher">手机验证完成即送<b>100</b>元代金券</p>
        <form class="registerform" action="{% url 'mx:register' %}" method="post" id="register-view">
            {% csrf_token %}
            <div class="register_box" id="register_box">
                <div class="input_zone">
                    <div class="input_l"><i>手&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机：</i></div>
                    <div class="input_r">
                        <input type="text" class="user_name" id="phone" name="phone" value="手机注册更享好礼"
                               style="color: rgb(204, 204, 204);font-size: 12px;">
                    </div>
                </div>
                <div class="input_zone">
                    <div class="input_l"><i>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：</i></div>
                    <div class="input_r">
                        <input type="password" name="password" class="psw1">
                    </div>
                </div>
                <div class="input_zone">
                    <div class="input_l"><i>确认 密码：</i></div>
                    <div class="input_r">
                        <input type="password" name="passwordchick" class="psw2">
                    </div>
                </div>
                <div class="meici_tag">
                    <input class="input_small_l" type="checkbox" value="1">
                    <span style="color: #6C6C6C;display: inline-block;">订阅美西时尚资讯</span>
                </div>
                <div class="meici_tag">
                    <button type="button" class="btn_register" id="subButton"> 注册 </button>
                    <br>
                    <div style="margin-top: 5px;text-align: right;">
                        已注册？
                        <a href="{% url 'mx:login' %}" style="color: #8E0C3A;">登录</a>
                    </div>
                    <p class="regInfo_msg"></p>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="footer">
    <div class="sub_nav">
        <ul class="clearfix">
            <li><a href="{% url 'mx:index' %}">首页</a></li>
            <li><a href="">关于美西</a></li>
            <li><a href="">媒体报道</a></li>
            <li><a href="">正品保障</a></li>
            <li><a href="">业务合作</a></li>
            <li><a href="">隐私声明</a></li>
            <li><a href="">加入美西</a></li>
            <li><a href="">网站地图</a></li>
            <li><a href="">联系我们</a></li>
        </ul>
    </div>
    <div class="copyright">
        <p>
            Copyright © 2008-2016 美西时尚-
            <a href="">高端时尚生活电商</a>
        </p>
        <p>
            <a href="">
                沪ICP备09001221号
            </a>
        </p>
    </div>
    <div class="safe">
        <a href=""><img src="{% static 'img/hy_83x30.png' %}"></a>
        <a href=""><img src="{% static 'img/ssgs.gif' %}"></a>
    </div>
</div>


</body>
</html>